# Default values for my-nextcloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: my-nextcloud

image:
  repository: new_app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "baranau_01"

env:
  - name: MYSQL_HOST
    value: 192.168.202.1
  - name: MYSQL_USER
    value: nextcloud
  - name: MYSQL_PASSWORD
    value: admin
  - name: MYSQL_DATABASE
    value: nextcloud
  - name: NEXTCLOUD_ADMIN_USER
    value: admin
  - name: NEXTCLOUD_ADMIN_PASSWORD
    value: admin

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  name: my-nextcloud-ingress
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: my-nextcloud.k8s-1.sa
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nfs:
  server: 192.168.37.105
  path: "/mnt/IT-Academy/nfs-data/sa2-25-23/baranau"
  readOnly: false
  vers: 3

persistentVolume:
    storage: 14Gi

nodeSelector: {}

tolerations: []

affinity: {}